### ISSUE TITLE
Trigger mentions list with a button instead of typing "@"

### ISSUE THREAD

**Issue by RamyAlReedy** [quill-mention/quill-mention#110]
Hi

Is there a method to trigger/show the mentions list using a button in the editor's toolbar or possibly a custom button?

What I'm looking for is the ability to have a button that inserts the "@" symbol in the editor and show the mention list.

Thanks.

**Comment by BakshinderSingh** [comment]
Looking for the same thing in my project also. We have a requirement of implementing that the mention functionality should work from button in our project.

**Comment by BakshinderSingh** [comment]
Hi @RamyAlReedy ,

Using the code below I am able to put a mention in Quill Editor using button outside editor.

const selection = selectedEditor.getSelection(true);
    selectedEditor.focus();
    selectedEditor.insertText(selection.index, '@');
    selectedEditor.blur();
    selectedEditor.focus();

give it a try.

Thanks

**Comment by RamyAlReedy** [comment]
@BakshinderSingh Thanks a lot for your help. Works perfectly!

**Comment by shamoons** [comment]
> Hi @RamyAlReedy ,
> 
> Using the code below I am able to put a mention in Quill Editor using button outside editor.
> 
> const selection = selectedEditor.getSelection(true);
> selectedEditor.focus();
> selectedEditor.insertText(selection.index, '@');
> selectedEditor.blur();
> selectedEditor.focus();
> 
> give it a try.
> 
> Thanks

Won't this still insert a `@`?

**Comment by andreivictor** [comment]
According to docs, there is a function for that: `openMenu('@')`. It is also presented in the demo page (https://afry.github.io/quill-mention/)

```
function onButtonClick() {
 quillEditor.getModule("mention").openMenu("@");
}
```
