### ISSUE TITLE
Ctrl Z empties the editor after integrating quill-mention module

### ISSUE THREAD

**Issue by k-lusine** [quill-mention/quill-mention#113]
I'm using react-quill package in my applications. Ctrl Z works as expected (there's a minor issue of not keeping initial value, which I fixed following this [suggestion](https://github.com/zenoamaro/react-quill/issues/511))

After integrating quill-mention module, Ctrl Z empties editor content. Any idea how it can be fixed, or why it happens?

Thanks

**Versions**
Quill-mention:  "2.1.5",
React-quill: "1.3.3",
Quill: "1.3.7"

**Comment by MadSpindel** [comment]
Could you try if 2.2.1 works better for you?

**Comment by k-lusine** [comment]
@MadSpindel No it's not fixed
