### ISSUE TITLE
onSelect should retrieve the mentioned word

### ISSUE THREAD

**Issue by guille-alibrate** [quill-mention/quill-mention#127]
Using onSelect event retrieves an object. But the value is not the raw value. It's something like html. Why not retrieving the original word too?

See:

```
onSelect: function (item, insertItem) {
        console.log(item)
        insertItem(item)
}
```

`item.value` returns:
`"<a href="http://miweb.com/biblioteca/5c6c5cd2e3ec1516d8252e81" target=_blank>lector de colectivo</a>"`. 

And I just want `lector de colectivo`.

**Comment by RonaldCrb** [comment]
i had the same issue, but i did fixed it with `editor.getText(0)` basically just adding the number zero as an argument will make quill to not add the html formatting when parsing text to the editor
