### ISSUE TITLE
Quill v2.0.0-dev.x support

### ISSUE THREAD

**Issue by AnishJoseph** [quill-mention/quill-mention#132]
Firrt off - thanks for creating this great plugin.
I was using Quill 1.3.6 with Quill mention and all was working well.
However to use the plugin 'quill better table' i needed to move quill to v2.0.0.3.
Quill mention fails here - my denotation char is '$' - however on typing $ nothing pops up - if i tab then the values pop up but i cannot choose any of the options.
Is there something i am missing or is it just that quill mention does not yet support quill v2.0.0

**Comment by eddieherm** [comment]
Ditto. I get the following error:

```
quill.mention.min.js:1 Uncaught TypeError: Class constructor  cannot be invoked without 'new'
    at new n (quill.mention.min.js:1)
    at o.create (quill-2.0.0-dev.3.min.js:7)
    at d.create (quill-2.0.0-dev.3.min.js:7)
    at h.insertAt (quill-2.0.0-dev.3.min.js:7)
    at h.insertAt (quill-2.0.0-dev.3.min.js:7)
    at h.insertAt (quill-2.0.0-dev.3.min.js:7)
    at d.insertAt (quill-2.0.0-dev.3.min.js:7)
    at d.insertAt (quill-2.0.0-dev.3.min.js:7)
    at d.insertAt (quill-2.0.0-dev.3.min.js:7)
    at e.default.insertEmbed (quill-2.0.0-dev.3.min.js:7)
```

**Comment by eddieherm** [comment]
I modified the .babelrc file to the following and I don't get the above error anymore:

`{
  "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "esmodules": true
          }
        }
      ]
    ],
    "plugins": [
        "@babel/plugin-transform-object-assign"
    ]
}
`

**Comment by Vbboi24** [comment]
@eddieherm , Can you please help me out here. Where exactly should i make this change. So that i can have both quill-better-table and quill-mention in my project ?

**Comment by pavan-shipmnts** [comment]
@Vbboi24 are you using babel to transpile your code? You can add it in babelconfig. It can be in .babelrc file, package.json or inside webpack config.

**Comment by pavan-shipmnts** [comment]
@Vbboi24  if you're using create-react-app you can use
```
    "presets": [
      [
        "react-app",
        {
          "useESModules": true
        }
      ]
    ],
```
useESModules option. It's stared to work for me.
