### ISSUE TITLE
How to insert mention into quill

### ISSUE THREAD

**Issue by Aidenkwok** [quill-mention/quill-mention#138]
Hello! if I store my text as a string like 'hello @mention' is it possible to insert it back into quill-js with the correct mention with quill-mention?

**Comment by bribar** [comment]
@Aidenkwok Can you explain a little more? Not following...do you have any example code?

Why are you storing the string 'hello @mention'?

**Comment by sridharpg** [comment]
I think he means adding twitter/linkedIn/Facebook profile url as links to the mentions.
