### ISSUE TITLE
Reload of previous quill.mention innerHTML content duplicates pre-existing <span contenteditable="false"> entries

### ISSUE THREAD

**Issue by pmcclintock** [quill-mention/quill-mention#174]
In my application, I am using the quilljs editor with the mention module to implement a notification template editor.  Unfortunately, each time I reload the pre-existing ql-editor's innerHTML content from my database into the application's quill.mention span content, (**document.getElementById("template").innerHTML = prevInnerHtmlContent;**) the resulting template span content contains an additional set of nested **<span contenteditable="false">** entries for each of the quill.mention **class="mention"** spans contained in the prevInnerHtmlContent string.

Is there a special process I should be using to reload a new instance of quill.mention with pre-existing HTML content with pre-existing quill.mention span content?  

Loading a given template two additional times beyond the initial quill.mention based addition of the token results in the following innerHTML span segments:

```html
<span class="mention" data-index="1" data-denotation-char="" data-id="[!$EntityName]" data-value="$EntityName">﻿<span contenteditable="false">﻿<span contenteditable="false">﻿<span contenteditable="false"><span class="ql-mention-denotation-char"></span>$EntityName</span>﻿</span>﻿</span>﻿</span>
```

Thanks for the assistance,
Paul McClintock

**Comment by getreworked** [comment]
@pmcclintock Were you able to resolve this issue? I'm experiencing the same thing

**Comment by pmcclintock** [comment]
No, I have not resolved the problem thus far. But instead simply modified my logic consuming the content to ignore the nested <span contenteditable="false" span directives.

**Comment by getreworked** [comment]
@pmcclintock I found this issue that resolved it for me. https://github.com/afry/quill-mention/issues/148

**Comment by pmcclintock** [comment]
Fantastic!  Thanks for the insight and assistance.  👍



Paul McClintock

Infor CRM BA

________________________________
