### ISSUE TITLE
Allow entering an email address even when the mention character is @

### ISSUE THREAD

**Issue by son-le** [quill-mention/quill-mention#177]
When the mention character is an `@` I can not enter an email address such as foo@example.com because the `@` in the email is treated like the start of another mention.

With the `isolateCharacter` option enabled, it is possible to ignore the `@` in the email, but still not possible to treat `@foo@example.com` as a single mention. Only everything preceding the ignored `@` is considered a mention, so only `@foo` is part of the mention.

The reason behind this behavior is because the mention char index is always the last `@` found.

I suggest adding a new option to customize that parsing behavior. The option's value would be a function that returns the index of the mention character and its default value would be the current behavior of returning the last index found. This is the approach I took in a fork to work around this problem.

Would love to merge the changes upstream. If this sounds like a good idea then I can open a PR. Or should there be a different way to support this scenario?

**Comment by blahbleepew** [comment]
did you ever find a solution to this?

**Comment by MadSpindel** [comment]
Sorry for late response @son-le but if you're interested in fixing this, I can give you commit access to this repository.

**Comment by son-le** [comment]
@MadSpindel Sure, I can add a fix for this.

**Comment by son-le** [comment]
Created PR #331 for this, but I don't have a codebase handy anymore that can verify this works as expected in a real project. Anybody here want to try this out and see if works for them?

**Comment by son-le** [comment]
Fixed in #252
