### ISSUE TITLE
onHover/onClick property for mentions

### ISSUE THREAD

**Issue by agarg5** [quill-mention/quill-mention#187]
It would be great to have a callback to detect when there is a hover or click over a mention that also gives the id for what is referenced. Even better would be a customizable popup that could open onHover.

**Comment by limbo-official** [comment]
+
 The on click callback for mentions is essential for project I'm working on, would really appreciate this functionality!

**Comment by limbo-official** [comment]
There's actually a [PR](https://github.com/afry/quill-mention/pull/184) for click callbacks
