### ISSUE TITLE
Add hover functionality

### ISSUE THREAD

**Issue by abhishekmatta999** [quill-mention/quill-mention#205]
I want to add hover functionality on the @mention tag added after selection and show an overlay with desired properties.
Add onHover on mention tags.

**Comment by GitRGoodman** [comment]
Yah, hover and onclick would be wonderful

**Comment by kovalforpublic** [comment]
@GitRGoodman onclick is already implemented. Just FYI. I may implement onhover soon.

**Comment by GitRGoodman** [comment]
@kovalforpublic I can't get it to work then, may I ask for an implementation exemple? (Sorry I know this might not be the right place to ask but I can't find a reference)

**Comment by kovalforpublic** [comment]
@GitRGoodman it's ok for me (but you can create a stackoverflow question and I'll transfer my answer there, for integrity purposes). Since people have questions I probably will add an example into readme. 
 
  this is an example I've added to readme.  
```javascript
    window.addEventListener('mention-clicked', (event) => {console.log('hovered: ', event)}, false);
```
   So, you just need to listen for **window:mention-clicked** (or "mention-hovered" in the near future ;) )
   
    I also created a [PR](https://github.com/afry/quill-mention/pull/227/) for "mention-hover" event. Please, you and @abhishekmatta999 feel free to add reactions so the holder of the project would have more incentive to merge it. 
     And thanks for raising the issue about unclear documantation for mention-click/hover event 👍 
      have a nice day

**Comment by GitRGoodman** [comment]
Thank you very much, correct me if I'm wrong tho, this way I wont' be able to get ant data from the mention click right?

**Comment by GitRGoodman** [comment]
Thank you, very informative and quick answer. Really a lifesaver

**Comment by kovalforpublic** [comment]
[PR](https://github.com/afry/quill-mention/pull/227/) was merged, now hover functionality is available, so the issue can be closed.
