### ISSUE TITLE
Programmatically insert mention on load

### ISSUE THREAD

**Issue by nicolasthy** [quill-mention/quill-mention#218]
Hi 👋 

First of all, thanks for this plugin, it helps a lot! I'm just having an issue for which I managed to find a dirty fix, but I'd rather use the methods provided by the plugin:

I'm trying to use the following code to insert a mention when the editor is created:
```js
// mention = {
//  denotationChar: "@"
//  index: "0"
//  firstName: string
//  lastName: string
// value: string (firstName + lastName)
// }

quill.getModule("mention").insertItem(mention, true);
```

Unfortunately I get the following error, any idea of what I'm doing wrong?
```
errorhandler.js:22 TypeError: Cannot read property 'index' of null
    at overload (quill.js:1686)
    at Quill.deleteText (quill.js:1210)
    at Mention.insertItem (quill.mention.esm.js:464)
```

Thanks in advance to whoever can give me a hand on this one 🙏

**Comment by nicolasthy** [comment]
Ok so I managed to fix it by doing the following:
```js
const mentionModule = quill.getModule("mention");
mentionModule.mentionCharPos = 0;
mentionModule.insertItem(mention, true);
```

Any reason why the `mentionCharPos` is `null` by default?

**Comment by flmthink** [comment]
> 好的，所以我设法通过执行以下操作来修复它：
> 
> ```js
> const mentionModule = quill.getModule("mention");
> mentionModule.mentionCharPos = 0;
> mentionModule.insertItem(mention, true);
> ```
> 
> 默认情况下`mentionCharPos`有什么原因吗？`null`

How did you solve it in the end? I also encountered this problem, and I don't know how to reproduce it.
