### ISSUE TITLE
quill mentioned people list

### ISSUE THREAD

**Issue by Himanshu-Negi-Dev** [quill-mention/quill-mention#253]
Hey @MadSpindel @cgross @cwhite-connectfirst @eltimn 

how do i get the list of mentioned people

suppose i have list of people 
const list = ["john", "jack", "anna", "himanshu"]

and i mentioned @john and @jack so how do i get the list contains these two names
eg => mentioned = ["john", "jack"];

if i remove @jack from mentioned so my mentioned list should like this 
eg => mentioned = ["john"]

How can i achieve this kind of functionality

Thanks

**Comment by dmostafiz** [comment]
did you get the solution ?? i am really
