### ISSUE TITLE
Fixed Quill v2.0.0-dev.4 implementation

### ISSUE THREAD

**Issue by artknight** [quill-mention/quill-mention#344]
Hi,
Here is the link to my the build - https://github.com/artknight/quill-mention/tree/master/dist. I did not do a fork (as I probably should have) so my repo is just a clone. However, all issues with v2 are fixed! 

Feel free to implement it, port it over :)

**Comment by BlazingUFO** [comment]
Give this guy a medal! Thousand thanks.

**Comment by quipo** [comment]
@artknight can you raise a PR to make it easy to get your changes accepted upstream?

**Comment by MadSpindel** [comment]
@artknight How about I give you access as contributor, and you implement your changes here?

**Comment by gsysaath** [comment]
Thank you so much !

**Comment by artknight** [comment]
@MadSpindel I am ok with being a contributor to this repo, and getting my changes in.
