### ISSUE TITLE
quill-mention should support Quill Version 2.0.0-rc.0

### ISSUE THREAD

**Issue by devaman** [quill-mention/quill-mention#361]
Issues found : 
- mentionDenotationChars when inserted at start of text is not opening the Dropdown
- After Selecting a value from dropdown and hitting enter is adding a new line in editor instead of inserting an embed

**Comment by csculley** [comment]
Marking as a duplicate of #362 even though this one is a bit older because I am blind 😅

**Comment by xie392** [comment]
> Issues found :
> 
> * mentionDenotationChars when inserted at start of text is not opening the Dropdown
> * After Selecting a value from dropdown and hitting enter is adding a new line in editor instead of inserting an embed

I wrote a simple implementation for my own use. You can [click to see it](https://github.com/xie392/quill-mention-react) it may be helpful to you.
