### ISSUE TITLE
FeatureRequest: Allow custom html when selecting an item

### ISSUE THREAD

**Issue by shyamal890** [quill-mention/quill-mention#44]
It would be great is can pass in a template for what should be pasted in the editor once an item is selected.

**Comment by silentsnooc** [comment]
That would be awesome - or is there any other way to perform an action once a item has been clicked inside the editor?

**Comment by bartholomej** [comment]
Yes, that would be awesome! 👍  Any plans with this feature?

**Comment by fridaystreet** [comment]
I'm pretty sure you can do this with the blotName option. Create your own blot with a different name 'mycustomblot' and it will use that to render it instead I assume.

**Comment by Ilijan91** [comment]
Any update for this?
