### ISSUE TITLE
Fix: KeyCodes for Quill 2

### ISSUE THREAD

**Issue by jurgen-reconcept** [quill-mention/quill-mention#88]
The current keycodes in constants/keys did not seem to work for Quill 2.x, so I pulled this repo and fixed them. I don't know how to contribute to this repo though, so here's my fix:

in constants/keys.js:
```
const Keys = {
  TAB: 'Tab',
  ENTER: 'Enter',
  ESCAPE: 'Escape',
  UP: 'ArrowUp',
  DOWN: 'ArrowDown',
};
```

in quill.mention.js some numbers were still hardcoded, replace them with the constant:
```
quill.keyboard.bindings[Keys.TAB].unshift(quill.keyboard.bindings[Keys.TAB].pop());
...
quill.keyboard.bindings[Keys.ENTER].unshift(quill.keyboard.bindings[Keys.ENTER].pop());
```

**Comment by MadSpindel** [comment]
Thank you @jurgen-reconcept. The best way is the fork the quill-mention repo to your own GitHub repo. Then you make the changes to your own branch and when you are done you make a pull request to this repo.

https://help.github.com/en/articles/creating-a-pull-request
